
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes an eye image and suggests a triage urgency level,
 * possible diagnoses, treatment suggestions, and detailed referral timing
 * based on comprehensive patient history and clinical findings.
 *
 * - analyzeEyeImage - A function that handles the eye image analysis and triage process.
 * - AnalyzeEyeImageInput - The input type for the analyzeEyeImage function.
 * - AnalyzeEyeImageOutput - The return type for the analyzeEyeImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeEyeImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the anterior eye, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  
  // Patient Demographics
  patientLocation: z.string().optional().describe("Patient's general location (e.g., city, province)."),
  sex: z.enum(['Male', 'Female']).optional().describe("Patient's sex."),

  // Core Complaint & History
  chiefComplaint: z.string().optional().describe('The primary reason for the consultation.'),
  historyOfPresentIllness: z.string().optional().describe('Detailed account of the current symptoms and their progression.'),
  
  // Ocular History
  ocularHistoryGeneral: z.string().optional().describe('General relevant ocular history (e.g., known conditions like glaucoma, AMD).'),
  priorOcularSurgery: z.boolean().optional().describe('Whether the patient has had prior ocular surgery (e.g., cataract, LASIK).'),
  wearsSpectacles: z.boolean().optional().describe('Whether the patient wears spectacles or contact lenses.'),
  eyeMedicationUsed: z.boolean().optional().describe('Whether the patient is currently using any eye medication (e.g., drops).'),
  ocularTrauma: z.boolean().optional().describe('Whether the patient has had ocular trauma.'),
  
  // Medical History
  pastMedicalHistory: z.string().optional().describe('Patient\'s overall past medical conditions and treatments (e.g., diabetes, hypertension).'),
  familyMedicalHistory: z.string().optional().describe('Relevant medical conditions in the patient\'s family (especially eye conditions).'),
  personalAndSocialHistory: z.string().optional().describe('Patient\'s lifestyle, habits (smoking, alcohol), occupation, and social environment.'),
  reviewOfSystems: z.string().optional().describe('A brief review of other body systems for relevant symptoms (e.g., fever, joint pain).'),

  // Physical Examination Findings
  // Right Eye (OD)
  visualAcuityOD_SC: z.string().optional().describe("Visual acuity (SC - without spectacles) for the Right Eye (e.g., 20/20, CF 2ft)."),
  visualAcuityOD_CC: z.string().optional().describe("Visual acuity (CC - with spectacles) for the Right Eye (e.g., 20/20, PHNI)."),
  colorTestingOD: z.string().optional().describe("Color vision testing results for the Right Eye (e.g., 14/14 Ishihara, mild red desaturation)."),
  amslerGridOD: z.string().optional().describe("AMSLER grid test results for the Right Eye (e.g., Normal, central metamorphopsia)."),
  pupilSizeOD: z.string().optional().describe("Pupil size for the Right Eye in mm (e.g., 3mm)."),
  pupilReactivityOD: z.string().optional().describe("Pupil reactivity to light for the Right Eye (e.g., Brisk, Sluggish, Non-reactive)."),
  pupilRapdOD: z.string().optional().describe("Presence or absence of Relative Afferent Pupillary Defect (RAPD) for the Right Eye (e.g., Present, Absent, Not Tested)."),
  palpationOD: z.string().optional().describe("Findings from eye palpation for the Right Eye (e.g., Soft, Non-tender, Firm)."),
  extraocularMusclesOD: z.string().optional().describe("Extraocular muscle movement findings for the Right Eye (e.g., Full, No EOM restrictions; or specific limitations like -2 limitation in adduction)."),
  grossExaminationOD: z.string().optional().describe("Gross examination findings for the Right Eye (e.g., Lids, Conjunctiva, Cornea)."),

  // Left Eye (OS)
  visualAcuityOS_SC: z.string().optional().describe("Visual acuity (SC - without spectacles) for the Left Eye (e.g., 20/20, CF 2ft)."),
  visualAcuityOS_CC: z.string().optional().describe("Visual acuity (CC - with spectacles) for the Left Eye (e.g., 20/20, PHNI)."),
  colorTestingOS: z.string().optional().describe("Color vision testing results for the Left Eye (e.g., 14/14 Ishihara, mild red desaturation)."),
  amslerGridOS: z.string().optional().describe("AMSLER grid test results for the Left Eye (e.g., Normal, central metamorphopsia)."),
  pupilSizeOS: z.string().optional().describe("Pupil size for the Left Eye in mm (e.g., 3mm)."),
  pupilReactivityOS: z.string().optional().describe("Pupil reactivity to light for the Left Eye (e.g., Brisk, Sluggish, Non-reactive)."),
  pupilRapdOS: z.string().optional().describe("Presence or absence of Relative Afferent Pupillary Defect (RAPD) for the Left Eye (e.g., Present, Absent, Not Tested)."),
  palpationOS: z.string().optional().describe("Findings from eye palpation for the Left Eye (e.g., Soft, Non-tender, Firm)."),
  extraocularMusclesOS: z.string().optional().describe("Extraocular muscle movement findings for the Left Eye (e.g., Full, No EOM restrictions; or specific limitations)."),
  grossExaminationOS: z.string().optional().describe("Gross examination findings for the Left Eye (e.g., Lids, Conjunctiva, Cornea)."),
});

export type AnalyzeEyeImageInput = z.infer<typeof AnalyzeEyeImageInputSchema>;

const AnalyzeEyeImageOutputSchema = z.object({
  triageUrgency:
    z.enum(['Urgent', 'Refer Within Week', 'Manage Locally'])
      .describe('The suggested triage urgency level based on the image analysis.'),
  reason: z.string().describe('The overall reasoning behind the triage urgency level and key findings.'),
  possibleDiagnoses: z.array(z.string()).describe("A list of potential differential diagnoses based on the provided information. Provide at least 2-3 possibilities if applicable."),
  treatmentSuggestions: z.array(z.string()).describe("General suggestions for initial management or treatment approaches if 'Manage Locally' is chosen, or supportive care pending referral. Provide 2-3 suggestions."),
  referralTimingDetails: z.string().describe("Specific guidance on the urgency and timeframe for referral (e.g., 'Immediate referral to ER', 'Refer to ophthalmologist within 24-48 hours', 'Routine ophthalmology follow-up in 1-2 weeks'), complementing the overall triage category.")
});

export type AnalyzeEyeImageOutput = z.infer<typeof AnalyzeEyeImageOutputSchema>;

export async function analyzeEyeImage(input: AnalyzeEyeImageInput): Promise<AnalyzeEyeImageOutput> {
  return analyzeEyeImageFlow(input);
}

const analyzeEyeImagePrompt = ai.definePrompt({
  name: 'analyzeEyeImagePrompt',
  model: 'googleai/gemini-2.0-flash',
  input: {schema: AnalyzeEyeImageInputSchema},
  output: {schema: AnalyzeEyeImageOutputSchema},
  prompt: `You are an expert ophthalmologist specializing in triaging eye conditions based on anterior eye images and comprehensive clinical data.

You will use the provided image and the following patient information to:
1. Determine the appropriate triage urgency level: Urgent, Refer Within Week, or Manage Locally.
2. List 2-3 possible differential diagnoses.
3. Suggest 2-3 general treatment or management approaches.
4. Provide specific details on the timing for referral.
5. Explain the overall reasoning for your decisions, highlighting key findings from all provided data.

Patient Information:
{{#if patientLocation}}Location: {{{patientLocation}}}{{/if}}
{{#if sex}}Sex: {{{sex}}}{{/if}}

{{#if chiefComplaint}}Chief Complaint: {{{chiefComplaint}}}{{/if}}
{{#if historyOfPresentIllness}}History of Present Illness: {{{historyOfPresentIllness}}}{{/if}}

Ocular History:
{{#if ocularHistoryGeneral}}  General: {{{ocularHistoryGeneral}}}{{/if}}
{{#if priorOcularSurgery}}  Prior Ocular Surgery: Yes{{else}}{{#if priorOcularSurgery_is_defined}}  Prior Ocular Surgery: No{{/if}}{{/if}}
{{#if wearsSpectacles}}  Wears Spectacles/Contacts: Yes{{else}}{{#if wearsSpectacles_is_defined}}  Wears Spectacles/Contacts: No{{/if}}{{/if}}
{{#if eyeMedicationUsed}}  Current Eye Medication: Yes{{else}}{{#if eyeMedicationUsed_is_defined}}  Current Eye Medication: No{{/if}}{{/if}}
{{#if ocularTrauma}}  Ocular Trauma: Yes{{else}}{{#if ocularTrauma_is_defined}}  Ocular Trauma: No{{/if}}{{/if}}

{{#if pastMedicalHistory}}Past Medical History: {{{pastMedicalHistory}}}{{/if}}
{{#if familyMedicalHistory}}Family Medical History: {{{familyMedicalHistory}}}{{/if}}
{{#if personalAndSocialHistory}}Personal and Social History: {{{personalAndSocialHistory}}}{{/if}}
{{#if reviewOfSystems}}Review of Systems: {{{reviewOfSystems}}}{{/if}}

Physical Examination Findings:
Right Eye (OD):
  {{#if visualAcuityOD_SC}}Visual Acuity (SC): {{{visualAcuityOD_SC}}}{{/if}}
  {{#if visualAcuityOD_CC}}Visual Acuity (CC): {{{visualAcuityOD_CC}}}{{/if}}
  {{#if colorTestingOD}}Color Testing: {{{colorTestingOD}}}{{/if}}
  {{#if amslerGridOD}}AMSLER Grid: {{{amslerGridOD}}}{{/if}}
  {{#if pupilSizeOD}}Pupil Size: {{{pupilSizeOD}}}{{/if}}
  {{#if pupilReactivityOD}}Pupil Reactivity: {{{pupilReactivityOD}}}{{/if}}
  {{#if pupilRapdOD}}RAPD: {{{pupilRapdOD}}}{{/if}}
  {{#if palpationOD}}Palpation: {{{palpationOD}}}{{/if}}
  {{#if extraocularMusclesOD}}Extraocular Muscles: {{{extraocularMusclesOD}}}{{/if}}
  {{#if grossExaminationOD}}Gross Examination: {{{grossExaminationOD}}}{{/if}}
Left Eye (OS):
  {{#if visualAcuityOS_SC}}Visual Acuity (SC): {{{visualAcuityOS_SC}}}{{/if}}
  {{#if visualAcuityOS_CC}}Visual Acuity (CC): {{{visualAcuityOS_CC}}}{{/if}}
  {{#if colorTestingOS}}Color Testing: {{{colorTestingOS}}}{{/if}}
  {{#if amslerGridOS}}AMSLER Grid: {{{amslerGridOS}}}{{/if}}
  {{#if pupilSizeOS}}Pupil Size: {{{pupilSizeOS}}}{{/if}}
  {{#if pupilReactivityOS}}Pupil Reactivity: {{{pupilReactivityOS}}}{{/if}}
  {{#if pupilRapdOS}}RAPD: {{{pupilRapdOS}}}{{/if}}
  {{#if palpationOS}}Palpation: {{{palpationOS}}}{{/if}}
  {{#if extraocularMusclesOS}}Extraocular Muscles: {{{extraocularMusclesOS}}}{{/if}}
  {{#if grossExaminationOS}}Gross Examination: {{{grossExaminationOS}}}{{/if}}

Photo: {{media url=photoDataUri}}

Based on all available information (image, history, and physical exam), provide a comprehensive analysis. Respond in the format specified by the output schema.
Ensure each list (diagnoses, treatments) has at least 2-3 distinct items if clinically appropriate.
For boolean fields in history (Prior Ocular Surgery, Wears Spectacles, Current Eye Medication, Ocular Trauma), their absence implies the information was not provided, not necessarily a 'No'. Only explicitly state Yes or No if the boolean value is present.
`,
});

// Helper to add '_is_defined' context for optional booleans in Handlebars
// This helps the prompt differentiate between 'false' and 'not provided'
function addDefinedFlagsForOptionalBooleans(input: AnalyzeEyeImageInput): any {
  const augmentedInput = { ...input } as any;
  if (input.priorOcularSurgery !== undefined) augmentedInput.priorOcularSurgery_is_defined = true;
  if (input.wearsSpectacles !== undefined) augmentedInput.wearsSpectacles_is_defined = true;
  if (input.eyeMedicationUsed !== undefined) augmentedInput.eyeMedicationUsed_is_defined = true;
  if (input.ocularTrauma !== undefined) augmentedInput.ocularTrauma_is_defined = true;
  return augmentedInput;
}


const analyzeEyeImageFlow = ai.defineFlow(
  {
    name: 'analyzeEyeImageFlow',
    inputSchema: AnalyzeEyeImageInputSchema,
    outputSchema: AnalyzeEyeImageOutputSchema,
  },
  async (rawInput) => {
    try {
      const inputWithFlags = addDefinedFlagsForOptionalBooleans(rawInput);
      const result = await analyzeEyeImagePrompt(inputWithFlags);
      if (!result.output) {
        console.error("Genkit analyzeEyeImagePrompt did not return a structured output. Full response object:", JSON.stringify(result, null, 2));
        let errorMessage = 'AI model did not return the expected output structure.';
        if (result.response?.candidates?.[0]?.finishReason) {
           errorMessage += ` Finish Reason: ${result.response.candidates[0].finishReason}.`;
        }
        if (result.response?.candidates?.[0]?.error) {
           errorMessage += ` Model Error: ${JSON.stringify(result.response.candidates[0].error)}.`;
        }
        throw new Error(errorMessage);
      }
      return result.output;
    } catch (flowError) {
      console.error("Error within analyzeEyeImageFlow:", flowError);
      throw flowError;
    }
  }
);

    
